### ISSUE TITLE
Version numbers starting with v

### ISSUE THREAD

**Issue by gowizzard** [thenativeweb/get-next-version#37] opened 2022-07-29 12:15 UTC
Hello, first super project! I have only a small question about it, may be that I just have not found the point, but how does it behave if you write a v before the version numbers? 

This is common in many Go projects and I just wanted to test your workflow in one of my projects, unfortunately this did not work 100% because I just version as follows: v1.3.12.

Will there still be the possibility to consider this in the cli tool and in the workflow?

That would be great! 

Many greetings 
Jonas

**Comment by gowizzard** [comment] 2022-07-29 12:57
@goloroden great, thank you. **I have just looked again and you are of course right.**

Unfortunately, this has nevertheless established itself. I have never thought about it myself. 

Thank you! 😊

**Comment by goloroden** [comment] 2022-07-30 13:45
Hey @gowizzard 👋 

I've given this a try today, and AFAICS it already works even with leading `v`s.
I'm going to add a few tests on this.

Could you do me a favor and try whether it already works for you, and give us some feedback?

**Comment by gowizzard** [comment] 2022-07-30 15:38
Hallo @goloroden 👋

that's right. I just tested it again with a new test repository. And it works, I just let myself specify the `v`'s up front in the output in the workflow. 

Now I am puzzled, I tested it yesterday on **an older repository** and there of course first I have no entries like feat: ... in the commits. Even when I set them, it didn't show me the correct version. I was already at `v1.2.9` and the action always gave `v1.2.0`. Unfortunately it is a private repository, so I can't link it here.

I will test it again on monday with an older repository. Do you have a workaround for repositories that previously worked with commit description without conventional commits? 

Otherwise thank you for your effort! I'll get back to you on monday. 😃

**Comment by goloroden** [comment] 2022-07-30 16:19
Unfortunately, no, we haven't (and we're probably not going to add anything on that, since it's a problem with the repo, not with the tool).

It would be interesting to have a look at that repo, but I understand that you can't share it since it's private (for good reasons, I guess 😉).

If you are able to come up with a reproducible test case, that you can share, this would be awesome 😊

**Comment by goloroden** [comment] 2022-07-30 16:20
PS: I'm going to close this issue, since we've figured out the thing about the `v` prefixes, and that's what this issue is about.

**Closed by goloroden** 2022-07-30 16:20 UTC

**Comment by gowizzard** [comment] 2022-08-01 08:12
Hi @goloroden 👋

I have now taken a closer look and checked the repository. It was indeed due to a tag that was not set on the master but on the development branch a very long time ago. Very annoying...

Fixed it for us and now your software works fine! Thanks again for your time! 😊

**Comment by goloroden** [comment] 2022-08-01 09:30
That's great, thanks for the update 😊
